# -*- coding: utf-8 -*-

from odoo import models, fields, api, _
from datetime import datetime


class ProductReportLog(models.Model):
    _name = 'drkds_pl2.product_report_log'
    _description = 'Product Report Generation Log'
    _order = 'create_date desc'

    name = fields.Char(string='Reference', required=True, copy=False, readonly=True, 
                       default=lambda self: _('New'))
    user_id = fields.Many2one('res.users', string='Generated By', required=True, 
                             default=lambda self: self.env.user)
    customer_id = fields.Many2one('res.partner', string='Customer', required=True)
    contact_id = fields.Many2one('res.partner', string='Contact')
    salesman_id = fields.Many2one('res.users', string='Salesman')
    price_level = fields.Selection([
        ('1', 'Price Level 1'),
        ('2', 'Price Level 2'),
        ('3', 'Price Level 3'),
        ('4', 'Price Level 4'),
        ('all', 'All Price Levels'),
    ], string='Price Level', required=True)
    doc_id = fields.Many2one('mrp.bom.cost.calculator', string='Source Document')
    create_date = fields.Datetime(string='Generated On', readonly=True)
    
    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', _('New')) == _('New'):
                vals['name'] = self.env['ir.sequence'].next_by_code('drkds_pl2.product_report_log') or _('New')
        return super(ProductReportLog, self).create(vals_list)